### ISSUE TITLE
Parameters.py missing regen attribute

### ISSUE THREAD

**Issue by mmcint** [sede-open/synthoseis#1]
i'm attempting to run the example model on my own machine, but running into an error with Parameters.py. There is no function called `regen` as referenced on line 746 in Horizon.py. 
see error below:

![Screenshot 2023-06-26 at 2 12 20 PM](https://github.com/sede-open/synthoseis/assets/135659585/cde088ed-9714-4b72-af98-2169c86140a4)

and here is the code from `Horizons.onlaps.insert_tilting_episodes()`:
![Screenshot 2023-06-26 at 2 14 22 PM](https://github.com/sede-open/synthoseis/assets/135659585/9e2a9277-975c-4ed5-b7fc-d33f280995e2)

i've searched through `Horizons` and `Parameters` and not able to  locate `regen`

i'm able to get the example model to run by commenting out line 746 in `Horizons.py`

**Comment by GiudiceVitor** [comment]
Hi @mmcint. Any idea on this topic? I'm running into the same problem and I'm wondering if just commenting line 746 solves the problem without compromising the rest of the code

**Comment by mmcint** [comment]
yes, just comment out line 746 and it should solve the problem. also, take a look at some of the open PRs. might help solve other issues

**Comment by gavargas22** [comment]
This issue is addressed in #11 

Thank you for pointing this out!

**Comment by gavargas22** [comment]
I did not encounter this issue while running the end 2 end process.  Maybe we can remove that line @tpmerrifield ?

**Comment by tpmerrifield** [comment]
Remove it, apologies. This is a remnant of a feature that tracked randomly selected parameters for regenerating a copy of the original model after changes were made to the code.
