### ISSUE TITLE
TypeError: RPMExample.__init__() got an unexpected keyword argument 'phic'

### ISSUE THREAD

**Issue by GiudiceVitor** [sede-open/synthoseis#10]
When trying to run default example, got the following error:
 
 TypeError: RPMExample.__init__() got an unexpected keyword argument 'phic'

Apparently RPMExemplo from `rockphysics/rmp_example.py` doesn't take `phic` and `athys_exp` as arguments. Still, `rockphysics/RockPropertyModels.py` at line `148` passes them as arguments.

**Comment by gavargas22** [comment]
Thank you for pointing this out!

I have fixed it in the pull request #11 

Those parameters were not expected by the RPM. But I also added kwargs argument if you need to pass some custom arguments to a RPM.

Can you please do another example run and see if things work for you? I have run the whole process and it is working for me. I also found a few other little bugs related to order of operations.
