### ISSUE TITLE
ModuleNotFoundError: No module named 'noise'

### ISSUE THREAD

**Issue by geokefe** [sede-open/synthoseis#24]
I'm trying to create a velocity using the velocity model module in synthoseis, but I got the following error message: Anyone with how to resolve should please share. Thanks.

The message: ........
No coherent noise will be inserted
Salt will be inserted. noise_stretch_factor = 1.31

Model folder: C:\scratch\synthoseis_example\seismic__2024.66208296_1
Creating directory: C:\scratch\synthoseis_example\seismic__2024.66208296_1
Creating directory: C:\scratch\temp_folder__2024.66208296_1

Keyfile created at C:\scratch\synthoseis_example\seismic__2024.66208296_1\seismicCube_2024.66208296.key
self.cfg.num_lyr_lut =  25000
onlap_layer_list =  [ 13  83 148 168]
Number of onlapping flags: 4
 ... horizon number for first onlap episode = 13
 ... number of channelFlags: 0
 ... horizon number for first channel episode: 0
	Indices for shallowest point in cube: 299, 40
Building random depth map at base of model
azi, dip, dipping_plane min/mean/max = 23.63049881287809, 0.15329132733246653, 0.00, 0.74, 1.49
current_depth_map min/mean/max = 12431.06, 12940.02, 13375.02
thickness_map min/mean/max = 0.79, 59.09, 134.95
Layer 0, depth_maps.shape = (300, 300)
Building Layer 1
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[24], line 51
     49 # Initialize and build the complex velocity model
     50 velocity_model = ComplexVelocityModel(config)
---> 51 model_data = velocity_model.build_model()
     53 # Plot the velocity model
     54 velocity_model.plot_velocity_model()

Cell In[24], line 18, in ComplexVelocityModel.build_model(self)
     15 os.makedirs(self.cfg['model_folder'], exist_ok=True)
     16 os.makedirs(self.cfg['temp_folder'], exist_ok=True)
---> 18 self.model = mn.build_model(user_json=self.cfg['config_file'], run_id=self.cfg['run_id'])
     20 return self.model

File ~\Desktop\seis\high_resolution_ML\synthoseis-master\main.py:26, in build_model(user_json, run_id, test_mode, rpm_factors)
     23 p.hdf_setup(os.path.join(p.temp_folder, "model_data.hdf"))
     24 # Build un-faulted depth maps and facies array
     25 depth_maps, onlap_list, fan_list, fan_thicknesses = \
---> 26     build_unfaulted_depth_maps(p)
     27 facies = create_facies_array(p, depth_maps, onlap_list, fan_list)
     29 # Build un-faulted geological models

File ~\Desktop\seis\high_resolution_ML\synthoseis-master\datagenerator\Horizons.py:1478, in build_unfaulted_depth_maps(parameters)
   1451 """
   1452     Build Unfaulted Depth Maps
   1453     --------------------------
   (...)
   1475         Generated fan thicknesses
   1476 """
   1477 horizons = RandomHorizonStack(parameters)
-> 1478 horizons.create_depth_maps()
   1479 # Insert onlap episodes
   1480 onlaps = Onlaps(
   1481     parameters, horizons.depth_maps, horizons.thicknesses, horizons.max_layers
   1482 )

File ~\Desktop\seis\high_resolution_ML\synthoseis-master\datagenerator\Horizons.py:643, in RandomHorizonStack.create_depth_maps(self)
    641     if self.cfg.verbose:
    642         print(f"Building Layer {i}")
--> 643     random_thickness_factor_map = self._random_layer_thickness()
    644 # Create the layer's thickness map using the random_thickness_factor_map
    645 thickness_map = self._create_thickness_map(random_thickness_factor_map, i)

File ~\Desktop\seis\high_resolution_ML\synthoseis-master\datagenerator\Horizons.py:403, in RandomHorizonStack._random_layer_thickness(self)
    399 low_thickness_factor = np.random.triangular(left=0.05, mode=0.2, right=0.95)
    401 high_thickness_factor = np.random.triangular(left=1.05, mode=1.8, right=2.2)
--> 403 thickness_factor_map = self._perlin(octave=rand_oct)
    404 thickness_factor_map -= thickness_factor_map.mean()
    405 thickness_factor_map *= (high_thickness_factor - low_thickness_factor) / (
    406     thickness_factor_map.max() - thickness_factor_map.min()
    407 )

File ~\Desktop\seis\high_resolution_ML\synthoseis-master\datagenerator\Horizons.py:99, in Horizons._perlin(self, base, octave, lac, do_rotate)
     98 def _perlin(self, base=None, octave=1, lac=1.9, do_rotate=True):
---> 99     import noise
    101     xsize = self.cfg.cube_shape[0]
    102     ysize = self.cfg.cube_shape[1]

ModuleNotFoundError: No module named 'noise'

**Comment by gavargas22** [comment]
hmm this looks like somehow the noise python module was not installed from the `pyproject.toml`.

What I would recommend is install the noise module directly on your environment:

```bash
poetry add noise
```

Is poetry working properly for you?

**Comment by geokefe** [comment]
Although poetry works for me, but when I try 'poetry add noise' it reported error. You may check the message below:

Using version ^1.2.2 for noise

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  - Installing noise (1.2.2): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-311
  creating build\lib.win-amd64-cpython-311\noise
  copying .\perlin.py -> build\lib.win-amd64-cpython-311\noise
  copying .\shader.py -> build\lib.win-amd64-cpython-311\noise
  copying .\shader_noise.py -> build\lib.win-amd64-cpython-311\noise
  copying .\test.py -> build\lib.win-amd64-cpython-311\noise
  copying .\__init__.py -> build\lib.win-amd64-cpython-311\noise
  running build_ext
  building 'noise._simplex' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/


  at ~\Conda\envs\synthoseis\Lib\site-packages\poetry\installation\chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with noise (1.2.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "noise (==1.2.2)"'.

**Comment by gavargas22** [comment]
Aha! It looks like you need to install Microsoft Visual C++ 14.0 or greater to install the module `noise`

**Download here:**

https://visualstudio.microsoft.com/visual-cpp-build-tools/

or a direct link: https://stackoverflow.com/questions/48541801/microsoft-visual-c-14-0-is-required-get-it-with-microsoft-visual-c-build-t


![image](https://github.com/user-attachments/assets/b095f144-b419-4ccf-896a-e924a0abf514)

After this it seems like you will be able to install the noise module. We had not really tested this extensively on Windows, so this is good to know to add to the documentation.

**Comment by geokefe** [comment]
The issue has been resolved. Thank you so much for assistance.
