### ISSUE TITLE
Synthoseis Modification

### ISSUE THREAD

**Issue by Tunjii10** [sede-open/synthoseis#26]
Hi,
     Great work done here. I wanted to ask a question regarding modifying the synthoseis code-base. I have a project in which I am trying to identify pipes or cables through their hyperbola contours created in seismic data or output from sensors. I have seen synthoseis as a valuable seismic data generator and I was wondering if its possible to introduce pipes or cables through the rock properties. I have been doing some digging as I am not so familiar with this  topic (geophysical materials), but I guess the idea would require creating a property that  can be deterministically fixed to a position in the seismic volume. Please, I want to know if this is possible, and if there are any pointers that could help towards this and is there any source material that can help me understand the formula's used in the codebase, especially in the rpm_example.py file. Thank you.

**Comment by tpmerrifield** [comment]
Hi, 
It may be possible to introduce pipes/cables into the model in a similar way that we add salt bodies, i.e. defining the shape, setting the "lith" flag to a new value, and then overwriting the vp, vs, rho values accordingly.

For example, in [Seismic.py line 1038](https://github.com/sede-open/synthoseis/blob/7f2baa0eeb96a4728a039a4ffed5cd4e6287b908/datagenerator/Seismic.py#L1038), we set rho = 2.17, vp = 4500, vs = 2250:

```# overwrite rho, vp, vs for salt if required
        if self.cfg.include_salt:
            # Salt. Set lith = 2.0
            i, j, k = np.where(lith == 2.0)
            mixed_properties.rho[i, j, k] = 2.17  # divide by 2 since lith = 2.0
            mixed_properties.vp[i, j, k] = 4500.0
            mixed_properties.vs[i, j, k] = 2250.0
            # Include fluidfactor rho, vp, vs inside salt body
            mixed_properties.rho_ff[i, j, k] = mixed_properties.rho[i, j, k]
            mixed_properties.vp_ff[i, j, k] = mixed_properties.vp[i, j, k]
            mixed_properties.vs_ff[i, j, k] = mixed_properties.vs[i, j, k]
```

<b>BUT:</b> this would only place the object into the synthetic model, and any of the resulting seismic noise that these objects would generate in real data would need to be generated and added.

**Comment by Tunjii10** [comment]
Thank you very much for your help @tpmerrifield
